### ISSUE TITLE
Can't start server. Mongoose connection error.

### ISSUE THREAD

**Issue by neelansh15** [rubyruins/daily-journal#1]
I ran `npm install` and tried running it on different ports. Do I need anything else installed? It is giving me this error:

![image](https://user-images.githubusercontent.com/53081208/82159893-3985f300-98af-11ea-84c7-11d046967bc8.png)

**Comment by rubyruins** [comment]
Nope, you don't need anything else installed. I tried running it on mine and it seems to be working fine. I had a few changes I had forgot to push (styling, route chaining) which I just did, but otherwise it seems to be alright. 

![image](https://user-images.githubusercontent.com/50259869/82185221-847f2500-9906-11ea-9722-168aabb505fe.png)

I think the useUnifiedTopology flag might be causing an issue, maybe you could check it out here? https://github.com/Automattic/mongoose/issues/8180

**Comment by rubyruins** [comment]
Also, have you tried running the server on port 3000?

**Comment by neelansh15** [comment]
Yes I tried running it on multiple ports. The `useUnifiedTopology` issue is the same that I am facing. It says changing that flag in a config file may help debug this issue, but I am not sure which config file they're talking about.

**Comment by rubyruins** [comment]
I think the config file is app.js. `useUnifiedTopology` might be causing this, but on removing that flag, it works but gives a deprecation warning :( Did you close the database connection the last time you used Mongoose? Perhaps [this ](http://findnerd.com/list/view/How-to-solve-MongoError-connect-ECONNREFUSED/2932/)could help.

**Comment by neelansh15** [comment]
![image](https://user-images.githubusercontent.com/53081208/82322890-dc945500-99f4-11ea-981d-61dd6e29300a.png)
Could this connection be the problem? Do I need to create and host a MongoDB on port `27017`?

**Comment by neelansh15** [comment]
I think this is a problem more about Mongoose connection errors than about this specific repo, so I'll close this issue.

**Comment by rubyruins** [comment]
Cool. Nope, you don't need to create a separate port. Mongo runs on port `27017` by default: as far as I know, that line creates a new DB if it doesn't exist or connects to it if it already exists.
